### ISSUE TITLE
Having trouble getting things to work

### ISSUE THREAD

**Issue by superfluke** [CMuell/Curseforge-Changelog-Compiler#1]
First problem I had was this
```
    from backports import configparser
ImportError: cannot import name 'configparser'
```
Changing `from backports import configparser` to `import configparser` seemed to fix that error. 
Now when running from the .bat I get
```
C:\python3\python.exe: Error while finding module specification for 'changelog.p
y' (AttributeError: module 'changelog' has no attribute '__path__')
```
Running as just `python changelog.py` avoids this no attribute __path__ but only produces an empty html. Also getting errors from what seems to be google oauth2

```
file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "C:\python3\lib\site-packages\googleapiclient\discovery_cache\__init__.py
", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python3\lib\site-packages\googleapiclient\discovery_cache\file_cache.
py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python3\lib\site-packages\googleapiclient\discovery_cache\file_cache.
py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python3\lib\site-packages\googleapiclient\discovery_cache\__init__.py
", line 41, in autodetect
    from . import file_cache
  File "C:\python3\lib\site-packages\googleapiclient\discovery_cache\file_cache.
py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
```

Did what I could to try and make it work, maybe I'm missing some library or screwed everything up by changing the import line from backport, but I could not get this program to run.

**Comment by CMuell** [comment]
Regarding the google oauth problem, I had noticed that but it hadn't affected the output, will look into the rest later today

**Comment by CMuell** [comment]
@superfluke Try executing the updated script. It will still have the oauth error for now but backports should import correctly

**Comment by superfluke** [comment]
Got around to trying it again and making progress with the program. Was getting an invalid json error using the normal setup. Changed the config file to use the cse id shown on the public search page for the custom google search rather than the one shown when created, which got rid of the invaild json. 

However, the program errors out if there are no search results, which I'm getting when the program tries to grab the changelog for fencejumper-1.12-1.0.3. Perhaps google just hasn't indexed the new one yet, should be some error catching for searches with 0 results.

**Comment by superfluke** [comment]
Also, only to most recent change log is grabbed. So for example, if I update from content tweaker 4.3.0 to content tweaker 4.4.1, I miss the change log from 4.4.0 which had the most content update and only see the small bug fix change log that was 4.4.1.

**Comment by CMuell** [comment]
@superfluke I've got a revision in the works that should fix all of the above ^
Instead of searching for the links directly to the changelogs, going to the /projects/modname/files and getting the changelog from the links there is 100% more reliable and easier to catch errors with. 

Thank you for the valuable feedback, and the changelogs between the two compared versions will also be included in the log when I get it up and running. Currently updating the dev branch every other night

**Comment by CMuell** [comment]
Issue fixed
